In [1]:
import numpy as np
import pandas as pd

print("The verison of numpy",np.__version__)
print("The verison of pandas",pd.__version__)

The verison of numpy 2.1.3
The verison of pandas 2.2.3

In [2]:
marks = np.array([78,85,92,67,88])
print("Marks:",marks)
print("type:",type(marks))
print(marks.size)

Marks: [78 85 92 67 88]
type: <class 'numpy.ndarray'>
5

In [3]:

print("Original:",marks)
print("Add 5:",marks + 5)
print("Multiply by 2:",marks*2)
print("Divide by 2:",marks/2)
print("Sqaure:",marks**2)

Original: [78 85 92 67 88]
Add 5: [83 90 97 72 93]
Multiply by 2: [156 170 184 134 176]
Divide by 2: [39.  42.5 46.  33.5 44. ]
Sqaure: [6084 7225 8464 4489 7744]

In [4]:
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())

Sum: 410
Mean: 82.0
Maximum: 92
Minimum: 67

In [5]:

print("First marks:",marks[0])
print("Second marks:",marks[1])
print("Last marks:",marks[-1])

First marks: 78
Second marks: 85
Last marks: 88

In [6]:
print("Index 1 to 3:",marks[1:4])
print("First three",marks[:3])
print("From index 2:",marks[2:])
print("Every second element:",marks[::2])

Index 1 to 3: [85 92 67]
First three [78 85 92]
From index 2: [92 67 88]
Every second element: [78 92 88]

In [7]:
student_marks=np.array([[78,85,92],[67,88,76],[90,95,89]])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)

In [8]:


print("mean of all values:",student_marks.mean())
print("Column-wise mean:",student_marks.mean(axis=0))
print("Row-wise mean:",student_marks.mean(axis=1))

mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
Row-wise mean: [85.         77.         91.33333333]

In [9]:
data={
    "Name":["Annu","Rahul","Kiran","Priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks": [85,91,76,88]
}
df=pd.DataFrame(data)
df

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [10]:
print("Shape",df.shape)
print("\nColumns:")
print(df.columns)

Shape (4, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')

In [11]:

print("Marks Column:")
print(df["Marks"])
print("\nBranch and Marks:")
print(df[["Branch","Marks"]])

Marks Column:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

Branch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88

In [12]:

print("First row:")
print(df.iloc[0])
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[:3])

First row:
Name      Annu
Branch     CSE
Marks       85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

In [13]:

print("First row:")
print(df.iloc[0])
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[:3])

First row:
Name      Annu
Branch     CSE
Marks       85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

In [14]:
high_scores=df[df["Marks"]>90]
high_scores

    Name Branch  Marks
1  Rahul   AIML     91

In [15]:
print("Students are from CSE:")
display(df[df["Branch"]=="CSE"])
print("Students scoring 85 or above:")
display(df[df["Marks"]>=85])

Students are from CSE:

    Name Branch  Marks
0   Annu    CSE     85
2  Kiran    CSE     76

Students scoring 85 or above:

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [16]:
print("Students are from CSE:")
display(df[df["Branch"]=="CSE"])
print("Students scoring 85 or above:")
display(df[df["Marks"]>=85])

Students are from CSE:

    Name Branch  Marks
0   Annu    CSE     85
2  Kiran    CSE     76

Students scoring 85 or above:

    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [18]:
'''Display only name and marks'''
print("name and marks:")
display(df[["Name","Marks"]])

name and marks:

    Name  Marks
0   Annu     85
1  Rahul     91
2  Kiran     76
3  Priya     88

In [20]:
print("Students with marks more than 80")
print(df[df["Marks"]>80])

Students with marks more than 80
    Name Branch  Marks
0   Annu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [22]:
print("Maximum marks of students")
print(df["Marks"].max())

Maximum marks of students
91

In [24]:
print("Students only from cse branch:")
print(df[df["Branch"]=="CSE"])

Students only from cse branch:
    Name Branch  Marks
0   Annu    CSE     85
2  Kiran    CSE     76

In [26]:
# Add an Attendance column to our existing DataFrame
df["Attendance"] = [90, 82, 88, 95]

print("Students with marks above 80 and attendance above 85:")
display(df[(df["Marks"] >= 80) & (df["Attendance"] >= 85)])

Students with marks above 80 and attendance above 85:

    Name Branch  Marks  Attendance
0   Annu    CSE     85          90
3  Priya   AIML     88          95